### ISSUE TITLE
repository.packageConfigs undefined after install

### ISSUE THREAD

**Issue by nickfun** [atlassian/lerna-semantic-release#47]
Hello, I am trying to get setup with lerna-semantic-release and am unable to take the first step of running `pre`.

I have a lerna repo in "independent" versioning mode. I installed with `npm install --save-dev lerna-semantic-release`. I made some changes to a package and commited them with git. I tried to run the pre command and I am getting this error:

```sh
$ node node_modules/.bin/lerna-semantic-release pre
/Users/nfunnell/Projects/react-components/node_modules/lerna/lib/PackageUtilities.js:73
      repository.packageConfigs.forEach(function (globPath) {
                               ^

TypeError: Cannot read property 'forEach' of undefined
    at Function.getPackages (/Users/nfunnell/Projects/react-components/node_modules/lerna/lib/PackageUtilities.js:73:32)
    at Object.getAllPackages (/Users/nfunnell/Projects/react-components/node_modules/lerna-semantic-release-io/io/lerna.js:7:29)
    at /Users/nfunnell/Projects/react-components/node_modules/lerna-semantic-release-pre/index.js:102:36
    at /Users/nfunnell/Projects/react-components/node_modules/git-head/index.js:15:5
    at /Users/nfunnell/Projects/react-components/node_modules/git-refs/index.js:95:18
    at /Users/nfunnell/Projects/react-components/node_modules/git-refs/index.js:31:7
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

I can run `lerna updated` and see there are are packages with changes available for publishing.

For reference here is info about my versions and workstation:

```sh
$ npm ls | grep lerna
├─┬ lerna@2.0.0-beta.31
├─┬ lerna-semantic-release@8.0.2
│ ├─┬ lerna-semantic-release-io@5.0.13
│ │ ├─┬ lerna-semantic-release-analyze-commits@4.1.0
│ │ ├── lerna-semantic-release-get-last-release@5.0.13
│ │ ├─┬ lerna-semantic-release-utils@4.0.13
│ ├── lerna-semantic-release-perform@4.0.13
│ ├─┬ lerna-semantic-release-post@5.0.13
│ └─┬ lerna-semantic-release-pre@4.1.0

$ uname -a
Darwin 0930-nfunnell 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
```

Please let me know if there is a workaround or if I should provide more information.

**Comment by jpnelson** [comment]
Can you let me know if this is fixed in the latest version? https://github.com/atlassian/lerna-semantic-release/pull/42 was just merged

**Comment by tricoder42** [comment]
@jpnelson The PR is merged but no new version has been released since then. I applied patch manually and it works for me 👍

**Comment by vovacodes** [comment]
@jpnelson @joscha could we please make a release, there is a bunch of unreleased changes already?

**Comment by nickfun** [comment]
@jpnelson thank you for your help so far. I have manually applied the diff of what I see in #42, but am still unable to use the `pre` script. Perhaps there are other dependent changes that I do not have in my manual change? I also recommend a full release of the project so that I can be sure I'm using the latest.

For reference, after applying #42 manually, I am able to have Lerna produce a list of packages that have changes, but semantic-release thinks there are no changes and does not take any action.

```sh
~/Projects/react-components (builds-testing *)
$ ./lerna updated
Lerna v2.0.0-beta.31
Independent Versioning Mode
Checking for updated packages...

- ui-components-alert-zzz
- ui-components-button-zzz

~/Projects/react-components (builds-testing *)
$ node node_modules/.bin/lerna-semantic-release pre
info:    Executing getNpmConfig in packages/ui-components-alert-zzz
info:    Executing makeSrConfig in packages/ui-components-alert-zzz
info:    Executing pre in packages/ui-components-alert-zzz
info:    Anaylzed 0 / 304 commits to determine type null for ui-components-alert-zzz
error:    message=There are no relevant changes, so no new version is released., code=ENOCHANGE
info:    Executing getNpmConfig in packages/ui-components-alert
info:    Executing makeSrConfig in packages/ui-components-alert
info:    Executing pre in packages/ui-components-alert
info:    Anaylzed 0 / 304 commits to determine type null for ui-components-alert
error:    message=There are no relevant changes, so no new version is released., code=ENOCHANGE
info:    Executing getNpmConfig in packages/ui-components-button-zzz
info:    Executing makeSrConfig in packages/ui-components-button-zzz
info:    Executing pre in packages/ui-components-button-zzz
info:    Anaylzed 0 / 304 commits to determine type null for ui-components-button-zzz
error:    message=There are no relevant changes, so no new version is released., code=ENOCHANGE
info:    Executing getNpmConfig in packages/ui-components-button
info:    Executing makeSrConfig in packages/ui-components-button
info:    Executing pre in packages/ui-components-button
info:    Anaylzed 0 / 304 commits to determine type null for ui-components-button
error:    message=There are no relevant changes, so no new version is released., code=ENOCHANGE
undefined
~/Projects/react-components (builds-testing *)
$
```

Also, as you can see, it examines every package in `packages/` even the ones with no changes.

**Comment by jpnelson** [comment]
This should be fixed (and released) now that https://github.com/atlassian/lerna-semantic-release/issues/49 is done. Please raise issues if you encounter further difficulty. Thanks!
