### ISSUE TITLE
 Cannot find module 'lerna/lib/Repository'

### ISSUE THREAD

**Issue by ashoksudani** [atlassian/lerna-semantic-release#91]
I have installed lerna-semantic-release and when tried to run command "lerna-semantic-release pre"; faced following error, interestingly I could not locate this file even manually in any directory.
module.js:549
    throw err;
    ^

Error: Cannot find module 'lerna/lib/Repository'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\work\tools\node\8.11.3\node_modules\lerna-semantic-release\node_modules\lerna-semantic-release-io\io\lerna.js:1:80)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

My package.json:
{
  "name": "package-name",
  "private": true,
  "scripts": {
    "lerna": "lerna",
    "lerna:pre-release": "lerna-semantic-release pre",
    "lerna:post-release": "lerna-semantic-release post"
  },
  "devDependencies": {
    "commitizen": "^2.10.1",
    "cz-lerna-changelog": "^1.2.1",
    "lerna": "^3.3.0",
    "lerna-semantic-release": "^9.1.0"
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-lerna-changelog"
    }
  }
}

**Comment by lukebatchelor** [comment]
Hiya, this is caused by using an unsupported version of lerna (most likely they've changed their repo structure at some point).

You'll either need to roll back to an older version or create a PR that updates this (it's most likely still available, just located somewhere else).

**Comment by PeterShershov** [comment]
@ashoksudani, what version did you use?

**Comment by ashoksudani** [comment]
@PeterShershov : I am using "lerna": "^3.0.0-rc.0"
